insert into congélateurs (id, nom, description) values (1, 'Golden', 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into congélateurs (id, nom, description) values (2, 'Blaxeland', 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis');
insert into congélateurs (id, nom, description) values (3, 'Stops', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh');
insert into congélateurs (id, nom, description) values (4, 'Pettinger', 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in');
insert into congélateurs (id, nom, description) values (5, 'Riccardi', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into congélateurs (id, nom, description) values (6, 'Toye', 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus');
insert into congélateurs (id, nom, description) values (7, 'Alan', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis');
insert into congélateurs (id, nom, description) values (8, 'Stopford', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis');
insert into congélateurs (id, nom, description) values (9, 'Fothergill', 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into congélateurs (id, nom, description) values (10, 'Rodear', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into congélateurs (id, nom, description) values (11, 'Poundsford', 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat');
insert into congélateurs (id, nom, description) values (12, 'McCritchie', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit');
insert into congélateurs (id, nom, description) values (13, 'Lorentz', 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum');
insert into congélateurs (id, nom, description) values (14, 'Carwithan', 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into congélateurs (id, nom, description) values (15, 'Eichmann', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien');
insert into congélateurs (id, nom, description) values (16, 'Mashro', 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet');
insert into congélateurs (id, nom, description) values (17, 'Clitherow', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum');
insert into congélateurs (id, nom, description) values (18, 'Illingsworth', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam');
insert into congélateurs (id, nom, description) values (19, 'Swindells', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in');
insert into congélateurs (id, nom, description) values (20, 'Shatliffe', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
